build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base:3.19
  amd64: ghcr.io/home-assistant/amd64-base:3.19
  armv7: ghcr.io/home-assistant/armv7-base:3.19

labels:
  org.opencontainers.image.title: "Cabin Assistant add-on: Claude Home"
  org.opencontainers.image.description: "AI-powered terminal interface with Claude Code CLI"
  org.opencontainers.image.source: "https://github.com/anthropics/claude-code"
  org.opencontainers.image.licenses: "MIT"