name: "Claude Home"
description: "AI-powered terminal interface with Claude Code CLI"
version: "2.0.3"
slug: "claude_home"
init: false

# Supported architectures
arch:
  - aarch64
  - amd64

# External resources
url: "https://github.com/cabinlab/hassio-addons/tree/main/claude-home"

# Web interface configuration
ingress: true
ingress_port: 7681
panel_icon: mdi:code-braces
panel_title: "Claude Home"
panel_admin: true

# Port configuration
ports:
  7681/tcp: 7681
ports_description:
  7681/tcp: "Web terminal (not required for ingress)"

# Add-on configuration options
options:
  claude_model: "haiku"
  theme: "dark"
  auto_claude: false
  verbose_logging: false
  max_turns: 10
  disable_telemetry: false
  terminal_bell: true
  ha_notifications: false
  notification_service: "persistent_notification"
  context_integration: true
  context_domains: "climate,sensor,binary_sensor,light,switch,weather"
  context_max_entities: 100

schema:
  claude_model: "list(haiku|sonnet|opus)"
  theme: "list(dark|light|system|high-contrast|auto)"
  auto_claude: "bool?"
  verbose_logging: "bool?"
  max_turns: "int(1,50)?"
  disable_telemetry: "bool?"
  terminal_bell: "bool?"
  ha_notifications: "bool?"
  notification_service: "list(persistent_notification|notify.notify|notify.mobile_app|notify.alexa_media|notify.telegram|custom)?"
  context_integration: "bool?"
  context_domains: "str?"
  context_max_entities: "int(10,500)?"

# Volume mapping for persistent storage
map:
  - config:rw    # Claude configuration and credentials only

# Service startup configuration
startup: services

# Home Assistant API access for service discovery
hassio_api: true

# Web UI access URL
webui: http://[HOST]:[PORT:7681]/