name: "Claude Home"
description: "AI-powered terminal interface with Claude Code CLI"
version: "1.4.1"
slug: "claude_home"
init: false

# Supported architectures
arch:
  - aarch64
  - amd64

# External resources
url: "https://github.com/anthropics/claude-code"

# Web interface configuration
ingress: true
ingress_port: 7681
panel_icon: mdi:code-braces
panel_title: "Claude Home"
panel_admin: true

# Port configuration
ports:
  7681/tcp: 7681
ports_description:
  7681/tcp: "Web terminal (not required for ingress)"

# Add-on configuration options
options:
  claude_model: "claude-3-5-sonnet-20241022"
  theme: "dark"
  verbose_logging: false
  max_turns: 10
  disable_telemetry: false
  terminal_bell: true
  ha_notifications: false
  notification_service: "persistent_notification"
  context_integration: true
  context_domains: "climate,sensor,binary_sensor,light,switch,weather"
  context_max_entities: 100

schema:
  claude_model: "list(claude-3-5-sonnet-20241022|claude-3-5-haiku-20241022|claude-3-opus-20240229|claude-3-sonnet-20240229|claude-3-haiku-20240307)?"
  theme: "list(dark|light|light-daltonized|dark-daltonized)?"
  verbose_logging: "bool?"
  max_turns: "int(1,50)?"
  disable_telemetry: "bool?"
  terminal_bell: "bool?"
  ha_notifications: "bool?"
  notification_service: "str?"
  context_integration: "bool?"
  context_domains: "str?"
  context_max_entities: "int(10,500)?"

# Volume mapping for persistent storage
map:
  - config:rw    # Claude configuration and credentials only

# Service startup configuration
startup: services

# Web UI access URL
webui: http://[HOST]:[PORT:7681]/