name: "Claude Home"
description: "AI-powered terminal and chat interface with Claude Code CLI"
version: "2.3.14"
slug: "claude_home"
init: false

# Supported architectures
arch:
  - aarch64
  - amd64

# External resources
url: "https://github.com/cabinlab/hassio-addons/tree/main/claude-home"

# Web interface configuration
ingress: true
ingress_port: 8080
panel_icon: mdi:robot-happy
panel_title: "Claude Home"
panel_admin: true

# Port configuration
ports:
  8080/tcp: 8080
  7681/tcp: null
  3000/tcp: null
  8001/tcp: null
ports_description:
  8080/tcp: "Main interface (responsive UI)"
  7681/tcp: "Web terminal (internal)"
  3000/tcp: "Chat interface (internal)"
  8001/tcp: "API Gateway (internal)"

# Add-on configuration options
options:
  claude_model: "haiku"
  theme: "dark"
  auto_claude: false
  verbose_logging: false
  disable_telemetry: false
  terminal_bell: true
  ha_notifications: false
  notification_service: "persistent_notification"
  working_directory: "/config"
  ha_url: ""
  ha_token: ""
  chat_interface: true
  openai_api_key: ""
  openai_model: "gpt-3.5-turbo"
  enable_openai_fallback: false
  gateway_port: 8001

schema:
  claude_model: "list(haiku|sonnet|opus)"
  theme: "list(dark|light|system|high-contrast|auto)"
  auto_claude: "bool?"
  verbose_logging: "bool?"
  disable_telemetry: "bool?"
  terminal_bell: "bool?"
  ha_notifications: "bool?"
  notification_service: "list(persistent_notification|notify.notify|notify.mobile_app|notify.alexa_media|notify.telegram|custom)?"
  working_directory: "list(/config|/config/claude-workspace|/root|/config/custom_components)?"
  ha_url: "str?"
  ha_token: "password?"
  chat_interface: "bool?"
  openai_api_key: "password?"
  openai_model: "str?"
  enable_openai_fallback: "bool?"
  gateway_port: "int(8000,8999)?"

# Volume mapping for persistent storage
map:
  - config:rw    # Claude configuration and credentials only

# Service startup configuration
startup: services

# Home Assistant API access
homeassistant_api: true
hassio_api: true

# Protection mode - when disabled, allows access to more files
host_network: false
host_pid: false  
host_ipc: false
hassio_role: manager
# This flag makes the protection mode toggle appear in the UI
full_access: true
# AppArmor provides security isolation
apparmor: true

# Web UI access URL
webui: http://[HOST]:[PORT:8080]/