name: "Claude Home"
description: "AI-powered terminal interface with Claude Code CLI"
version: "1.2.2"
slug: "claude_home"
init: false

# Supported architectures
arch:
  - aarch64
  - amd64

# External resources
url: "https://github.com/anthropics/claude-code"

# Web interface configuration
ingress: true
ingress_port: 7681
panel_icon: mdi:code-braces
panel_title: "Claude Home"
panel_admin: true

# Port configuration
ports:
  7681/tcp: 7681
ports_description:
  7681/tcp: "Web terminal (not required for ingress)"

# Add-on configuration options
options: {}
schema: {}

# Volume mapping for persistent storage
map:
  - config:rw    # Claude configuration and credentials only

# Service startup configuration
startup: services

# Web UI access URL
webui: http://[HOST]:[PORT:7681]/