name: "APC UPS Daemon"
description: "Monitor APC UPS devices with native apcupsd integration"
version: "2.0.1"
slug: "apcupsd"
init: false

# Supported architectures
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386

# External resources
url: "https://github.com/cabinlab/hassio-addons"

# Service startup configuration
startup: services
boot: auto

# Home Assistant API access
hassio_api: true
hassio_role: manager

# Volume mapping for scripts and configuration
map:
  - share:rw

# USB device access for UPS communication
devices:
  - "/dev/usb/:/dev/usb/:rwm"

# Network port for apcupsd daemon
ports:
  3551/tcp: 3551
ports_description:
  3551/tcp: "APC UPS daemon communication port"

# Add-on configuration options
options:
  ups_name: "APC UPS"
  cable_type: "usb"
  ups_protocol: "usb"
  device: ""
  battery_shutdown_level: 5
  minutes_before_shutdown: 3
  max_runtime_seconds: 0
  shutdown_delay: 0
  port: 3551
  timeout_seconds: 60
  advanced_options: []

# Configuration schema
schema:
  ups_name: "str?"
  cable_type: "list(usb|smart|simple|ether|940-0024C|940-0095A|940-0095B|940-0095C|940-1524C|940-0128A|MAM-04-02-2000)?"
  ups_protocol: "list(usb|net|apcsmart|dumb|pcnet|snmp|test|modbus)?"
  device: "str?"
  battery_shutdown_level: "int(1,95)?"
  minutes_before_shutdown: "int(1,60)?"
  max_runtime_seconds: "int(0,7200)?"
  shutdown_delay: "int(0,300)?"
  port: "int(1024,65535)?"
  timeout_seconds: "int(10,600)?"
  advanced_options:
    - key: str
      val: str

# Panel configuration
panel_icon: mdi:battery-plus
panel_title: "APC UPS Monitor"