name: "APC UPS Daemon"
description: "Monitor APC UPS devices with native apcupsd integration"
version: "2.0.6"
slug: "apcupsd"
init: false

# Supported architectures
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386

# External resources
url: "https://github.com/cabinlab/hassio-addons"

# Service startup configuration
startup: services
boot: auto

# Home Assistant API access for power control
hassio_api: true
hassio_role: manager

# Volume mapping for scripts and configuration
map:
  - share:rw

# USB device access for UPS communication
devices:
  - "/dev/usb/:/dev/usb/:rwm"

# Network port for apcupsd daemon
ports:
  3551/tcp: 3551
ports_description:
  3551/tcp: "APC UPS daemon communication port"

options:
  name: "APC UPS"
  cable: "usb"
  type: "usb"
  device: ""
  battery_level: 10
  timeout_minutes: 5
  auto_discovery: true

schema:
  name: "str?"
  cable: "list(usb|smart|simple|ether|940-0024C|940-0095A|940-0095B|940-0095C|940-1524C|940-0128A|MAM-04-02-2000)"
  type: "list(usb|net|apcsmart|dumb|pcnet|snmp|test|modbus)"
  device: "str?"
  battery_level: "int(5,95)?"
  timeout_minutes: "int(1,60)?"
  auto_discovery: "bool?"

# Panel configuration
panel_icon: mdi:battery-plus
panel_title: "APC UPS Monitor"