name: "APC UPS Daemon"
description: "Monitor APC UPS devices with native apcupsd integration"
version: "2.0.1"
slug: "apcupsd"
init: false

# Supported architectures
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386

# External resources
url: "https://github.com/cabinlab/hassio-addons"

# Service startup configuration
startup: services
boot: auto

# Home Assistant API access
hassio_api: true
hassio_role: manager

# Volume mapping for scripts and configuration
map:
  - share:rw

# USB device access for UPS communication
devices:
  - "/dev/usb/:/dev/usb/:rwm"

# Network port for apcupsd daemon
ports:
  3551/tcp: 3551
ports_description:
  3551/tcp: "APC UPS daemon communication port"

# Add-on configuration options
options:
  # Basic UPS Configuration
  ups_name: "APC UPS"
  connection_cable: "usb"
  ups_type: "usb" 
  device_path: ""
  
  # Power Management Thresholds
  shutdown_battery_percent: 5
  shutdown_minutes_on_battery: 3
  maximum_battery_runtime_seconds: 0
  graceful_shutdown_delay_seconds: 0
  
  # Network Communication Settings  
  daemon_port: 3551
  network_timeout_seconds: 60
  
  # Advanced Configuration (Expert Users)
  custom_apcupsd_options: []

# Configuration schema with improved descriptions
schema:
  ups_name: "str?"
  connection_cable: "list(usb|smart|simple|ether|940-0024C|940-0095A|940-0095B|940-0095C|940-1524C|940-0128A|MAM-04-02-2000)?"
  ups_type: "list(usb|net|apcsmart|dumb|pcnet|snmp|test|modbus)?"
  device_path: "str?"
  shutdown_battery_percent: "int(1,95)?"
  shutdown_minutes_on_battery: "int(1,60)?"
  maximum_battery_runtime_seconds: "int(0,7200)?"
  graceful_shutdown_delay_seconds: "int(0,300)?"
  daemon_port: "int(1024,65535)?"
  network_timeout_seconds: "int(10,600)?"
  custom_apcupsd_options:
    - key: str
      val: str

# Panel configuration
panel_icon: mdi:battery-plus
panel_title: "APC UPS Monitor"