name: Build and Publish Claude Home

on:
  push:
    branches:
      - main
    paths:
      - 'claude-home/Dockerfile'
      - 'claude-home/build.yaml'
      - 'claude-home/requirements.txt'
      - 'claude-home/package*.json'
      - 'claude-home/chat_gateway_mcp.py'
      - 'claude-home/supervisord.conf'
      - 'claude-home/ui/**'
      - 'claude-home/hass-mcp-lite/**'
      - '.github/workflows/build-claude-home.yml'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to build (e.g., 2.0.0)'
        required: false
        default: 'latest'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: cabinlab/claude-home

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value=${{ github.event.inputs.version }},enable=${{ github.event_name == 'workflow_dispatch' }}

      - name: Determine Dockerfile location
        id: dockerfile
        run: |
          if [ -f "dev-workspace/standalone/Dockerfile" ]; then
            echo "path=dev-workspace/standalone" >> $GITHUB_OUTPUT
            echo "Using standalone Dockerfile"
          else
            echo "path=claude-home" >> $GITHUB_OUTPUT
            echo "Using add-on Dockerfile"
          fi

      - name: Copy core scripts if needed
        if: steps.dockerfile.outputs.path == 'dev-workspace/standalone'
        run: |
          if [ -d "dev-workspace/core" ]; then
            cp -r dev-workspace/core dev-workspace/standalone/
          fi

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ${{ steps.dockerfile.outputs.path }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            BUILD_FROM=ghcr.io/hassio-addons/debian-base:7.8.3

      - name: Update Home Assistant add-on
        if: success() && startsWith(github.ref, 'refs/tags/v')
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          sed -i "s|ghcr.io/cabinlab/claude-home:.*|ghcr.io/cabinlab/claude-home:${VERSION}|g" claude-home/build.yaml || true
          
          # Create PR if changes were made
          if git diff --quiet; then
            echo "No changes to build.yaml"
          else
            git config --global user.name 'github-actions[bot]'
            git config --global user.email 'github-actions[bot]@users.noreply.github.com'
            git checkout -b update-addon-${VERSION}
            git add claude-home/build.yaml
            git commit -m "Update Claude Home to ${VERSION}"
            git push origin update-addon-${VERSION}
            gh pr create --title "Update Claude Home to ${VERSION}" --body "Automated update from container build"
          fi